### ISSUE TITLE
Wind directions are sometimes wrong

### ISSUE THREAD

**Issue by mortenwh** [metno/met-sar-vind#7]
Ref emails with Erik Samuelsen. Needs to be debugged and solved.

**Comment by mortenwh** [comment]
![20211122_06UTC_feilvindretning](https://user-images.githubusercontent.com/109061/210338528-e43a6d5d-e048-48b1-ba2d-4487a3672ba0.png)

**Comment by mortenwh** [comment]
This should be the correct datasets:

* https://nbstds.met.no/thredds/catalog/NBS/S1A/2021/11/22/IW/catalog.html?dataset=nbs/S1A/2021/11/22/IW/S1A_IW_GRDM_1SDV_20211122T060056_20211122T060123_040680_04D3AB_B0A2.nc
* https://thredds.met.no/thredds/catalog/aromearcticarchive/2021/11/22/catalog.html?dataset=aromearcticarchive/2021/11/22/arome_arctic_vtk_20211122T06Z.nc

**Comment by frodedinessen** [comment]
I have used the files mentioned above but are not able to reproduce this error. When running on my local computer using the following command:
python ./run_sarwind.py -s /home/froded/software/sarwind/met-sar-vind/tests/files/S1A_IW_GRDM_1SDV_20211122T060056_20211122T060123_040680_04D3AB_B0A2.nc -w /home/froded/software/sarwind/met-sar-vind/tests/files/arome_arctic_vtk_20211122T06Z.nc -n /home/froded/software/sarwind/met-sar-vind/tests/files/WIND_S1A_IW_GRDM_1SDV_20211122T060056_20211122T060123_040680_04D3AB_B0A2.nc

Loding the data in diana it looks like:
![image](https://user-images.githubusercontent.com/45628488/211775850-8a35817e-d534-49dd-946d-4abc7ea32f5f.png)

**Comment by frodedinessen** [comment]
Generating the SAR-wind product on ubuntu@157.249.96.220 gave the result as show below. Still not able to reproduce the error. 
![image](https://user-images.githubusercontent.com/45628488/218417695-4beb39dd-7ea0-485c-97e3-20637bdd3140.png)
